[account]
name = "xxx"  # 姓名 【如"张三"】
ID = "xxx"  # 学号 【如U202115413】
password = "xxx"  # 华中大统一认证密码

[time]
date = "2024-11-17"  # 预约日期【如"2024-09-01","2024-11-17"】
start_time = "14"  # 开始时间【如"8","14"】

[court]
name = "游泳馆"  # 场馆名称【可选项为"光谷体育馆","西边体育馆","游泳馆"】
number = "1"  # 场地编号【可选项为"光谷体育馆:1~22","西边体育馆:1~9","游泳馆:1~9"】

[partner]
name = "xxx"  # 同伴姓名 【如"张三"】
ID = "xxx"  # 同伴学号 【如"U202315617"】
password = "xxx"  # 同伴密码 
card_type = "1"  # 1:学生 2:教职工 3:校外人员